//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.05.11 at 08:32:25 PM MDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:astm-org:CCR", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.astm.ccr;
